### ISSUE TITLE
dmatrix_Kdomega not initialized before use in regcoil_build_matrices

### ISSUE THREAD

**Issue by jcschmitt** [landreman/regcoil#15]
This happens when I use regcoil from stellopt.  The sensitivity option is .eq. to 1, so the allocation (line 141) is never performed.

Then around, line 864, stellopt will halt when regcoil tries to do this:
dmatrix_Kdomega = dmatrix_Kdomega*dtheta_coil*dzeta_coil

I didn't poke around to see if dmatrix_Kdomega was needed for anything else, but maybe restricting the call with an "if" statement is sufficient?  LIke this:
if (sensitivity_option > 1)  dmatrix_Kdomega = dmatrix_Kdomega*dtheta_coil*dzeta_coil

**Comment by jcschmitt** [comment]
I tested it with the following, and it seems to work for me (at least one test case):

    if (sensitivity_option > 1) dmatrix_Kdomega = dmatrix_Kdomega*dtheta_coil*dzeta_coil

**Comment by ejpaul** [comment]
Thanks for catching this. I moved that line inside the "if (sensitivity_option > 2 .or. fixed_norm_sensitivity_option)" in the last commit. Do you want to check if that fixes the issue?

**Comment by jcschmitt** [comment]
The fix seems to work.  I do run into another problem with dsysv, however:
 !!!!!! Error in LAPACK DSYSV: INFO =           16

But, I don't think this is related to this particular issue, and it is quite possible that it is something in stellopt that is the ultimate source of this new(er) issue.    If I keep running into this new(er) problem, I will open up a separate issue.  For now, I think this can be closed.
Thanks for the quick fix!
