### ISSUE TITLE
Compiling Manual

### ISSUE THREAD

**Issue by tmqian** [landreman/regcoil#18]
I found a .sty file missing from the manual

```
! LaTeX Error: File `commath.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
```

Adding this file to the dir resolved the problem ([link](http://tug.ctan.org/tex-archive/macros/latex/contrib/commath/commath.sty)). Maybe you can add this file to the git repository?

I got a second error:
```
kpathsea: Running mktexmf pplb7t
! I can't find file `pplb7t'.
<*> ...:=ljfour; mag:=1; nonstopmode; input pplb7t
```

This prevented me from generating the PDF. Do you have any suggestions?

**Comment by landreman** [comment]
The manual can now be found online [here](http://landreman.github.io/regcoil/regcoilManual.pdf), and I updated the README to point users there. Regarding those error messages, I had never seen either before today. Today I saw the 'commath.sty' error for the 1st time, when setting up a Github Action to build and post the manual; this error was resolved by adding 'apt-get install texlive-science'. So perhaps your latex distribution is missing a package like this. I've never seen the pp1b7t error.

**Comment by tmqian** [comment]
Thanks for uploading the manual as a PDF. 

The missing STY occurred on both my local computer and pppl's portal cluster. 
The missing file `pplb7t' only occured on my local computer. 

After scp-ing the commath.sty to cluster, I was able to run the makefile successfully without any change, and generate the 26pg PDF. 

Since that resolved the problem I am closing this issue.
